import '../styles/quasar.styl'
import 'quasar-framework/dist/quasar.ie.polyfills'
import lang from 'quasar-framework/i18n/pt-br'
import 'quasar-extras/animate'
import 'quasar-extras/material-icons'

import {
    Quasar,
    QAlert,
    QBtn,
    QCheckbox,
    QCollapsible,
    QField,
    QIcon,
    QInnerLoading,
    QInput,
    QItem,
    QItemMain,
    QItemSide,
    QLayout,
    QLayoutHeader,
    QLayoutDrawer,
    QList,
    QListHeader,
    QPage,
    QPageContainer,
    QPageSticky,
    QPagination,
    QPopover,
    QRadio,
    QRouteTab,
    QSearch,
    QSelect,
    QTable,
    QTabs,
    QTab,
    QTabPane,
    QToolbar,
    QToolbarTitle,
    QTooltip,
    QVideo,
    QWindowResizeObservable,
    QSpinner,
    QDatetime,
    QModal,
    QModalLayout,
    QAjaxBar,
    QCard,
    QCardTitle,
    QCardMain,
    QCardMedia,
    QCardSeparator,
    QCardActions,
    QTr,
    QTd,
    QChip,
    QToggle,
    QBtnGroup,
    QTimeline,
    QTimelineEntry,
    QAutocomplete,
    BackToTop,
    CloseOverlay,
    Ripple,
    AppFullscreen,
    Dialog,
    Loading,
    Notify,
    SessionStorage,
    LocalStorage
} from 'quasar'

const quasarConfig = {
    config: {},
    components: {
        QAlert,
        QBtn,
        QCheckbox,
        QCollapsible,
        QField,
        QIcon,
        QInnerLoading,
        QInput,
        QItem,
        QItemMain,
        QItemSide,
        QLayout,
        QLayoutHeader,
        QLayoutDrawer,
        QList,
        QListHeader,
        QPage,
        QPageContainer,
        QPageSticky,
        QPagination,
        QPopover,
        QRadio,
        QRouteTab,
        QSearch,
        QSelect,
        QTable,
        QTabs,
        QTab,
        QTabPane,
        QToolbar,
        QToolbarTitle,
        QTooltip,
        QVideo,
        QWindowResizeObservable,
        QSpinner,
        QDatetime,
        QModal,
        QModalLayout,
        QAjaxBar,
        QCard,
        QCardTitle,
        QCardMain,
        QCardMedia,
        QCardSeparator,
        QCardActions,
        QTr,
        QTd,
        QChip,
        QToggle,
        QBtnGroup,
        QTimeline,
        QTimelineEntry,
        QAutocomplete
    },
    directives: {
        BackToTop,
        CloseOverlay,
        Ripple
    },
    plugins: {
        AppFullscreen,
        Dialog,
        Loading,
        Notify,
        SessionStorage,
        LocalStorage
    },
    i18n: lang
}

export { quasarConfig, Quasar }
